--- #YAML:1.0
name:               Git-SVNReplay
version:            1.0001
abstract:           ~
author:
    - Paul Miller <jettero@cpan.org>
license:            GPL
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Date::Parse:          0
    DBM::Deep:            0
    File::Path:           0
    File::Slurp:          0
    Getopt::Long:         0
    IPC::System::Simple:  0
    perl:                 5.006001
    Pod::Usage:           0
    Term::GentooFunctions:  0
resources:
    repository:  http://github.com/jettero/git-svn-replay
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
keywords:
    - git
    - svn
